version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: custodia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Core.123
      MYSQL_DATABASE: custodiaCRM
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: custodia-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Core.123
    command: ["java", "-jar", "app.jar"]

volumes:
  mysql_data:
