name: Java CI with Maven and MySQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: custodiaCRM
          MYSQL_USER: custodiauser
          MYSQL_PASSWORD: custodiapass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set environment variables
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_NAME=custodia" >> $GITHUB_ENV
          echo "DB_USER=custodiauser" >> $GITHUB_ENV
          echo "DB_PASSWORD=custodiapass" >> $GITHUB_ENV

      - name: Build with Maven
        run: ./mvnw clean install
